In [1]:
import numpy as np

In [2]:
# === Bloque 1: Funciones de activación ===
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

In [3]:
# === Bloque 2: Inicialización de datos de entrada ===
np.random.seed(42)
input_size = 4   # Tamaño del vector de entrada x_t
hidden_size = 3  # Tamaño del vector de estado oculto h_t y celda C_t

x_t = np.random.rand(input_size, 1)          # Entrada actual
h_prev = np.random.rand(hidden_size, 1)      # Estado oculto anterior
C_prev = np.random.rand(hidden_size, 1)      # Estado de celda anterior

print("=== Entrada actual x_t ===\n", x_t)
print("=== Estado oculto anterior h_{t-1} ===\n", h_prev)
print("=== Estado de celda anterior C_{t-1} ===\n", C_prev)

=== Entrada actual x_t ===
 [[0.37454012]
 [0.95071431]
 [0.73199394]
 [0.59865848]]
=== Estado oculto anterior h_{t-1} ===
 [[0.15601864]
 [0.15599452]
 [0.05808361]]
=== Estado de celda anterior C_{t-1} ===
 [[0.86617615]
 [0.60111501]
 [0.70807258]]


In [4]:
# === Bloque 3: Inicialización de pesos y sesgos ===
W_f = np.random.rand(hidden_size, hidden_size + input_size)
b_f = np.random.rand(hidden_size, 1)

W_i = np.random.rand(hidden_size, hidden_size + input_size)
b_i = np.random.rand(hidden_size, 1)

W_C = np.random.rand(hidden_size, hidden_size + input_size)
b_C = np.random.rand(hidden_size, 1)

W_o = np.random.rand(hidden_size, hidden_size + input_size)
b_o = np.random.rand(hidden_size, 1)

In [6]:
# === Bloque 4: Concatenación de h_{t-1} y x_t ===
concat = np.vstack((h_prev, x_t))
print("\n=== Concatenación [h_{t-1}; x_t] ===\n", concat)


=== Concatenación [h_{t-1}; x_t] ===
 [[0.15601864]
 [0.15599452]
 [0.05808361]
 [0.37454012]
 [0.95071431]
 [0.73199394]
 [0.59865848]]


In [8]:
# === Bloque 5: Cálculo de las puertas ===
# Puerta de olvido f_t
f_t = sigmoid(W_f @ concat + b_f)
print("\n🔑 Puerta de OLVIDO f_t (cuánto olvidar del pasado) ===\n", f_t)
print("Nota: valores cercanos a 1 mantienen la memoria anterior (C_{t-1}), mientras que valores cercanos a 0 la olvidan.")

# Puerta de entrada i_t
i_t = sigmoid(W_i @ concat + b_i)
print("\n🆕 Puerta de ENTRADA i_t (cuánto nuevo aprender) ===\n", i_t)
print("Nota: valores cercanos a 1 permiten que la nueva información propuesta (\u0303C_t) entre a la memoria; valores cercanos a 0 la bloquean.")

# Candidato de celda C~_t
C_tilde = tanh(W_C @ concat + b_C)
print("\n📥 Estado CANDIDATO \u0303C_t (información propuesta) ===\n", C_tilde)
print("Nota: este es el nuevo contenido que podría ser guardado en la celda, sujeto a la aprobación de i_t.")

# Estado de celda C_t
C_t = f_t * C_prev + i_t * C_tilde
print("\n🧠 ESTADO de CELDA C_t (memoria combinada) ===\n", C_t)
print("Nota: C_t combina lo que decidimos olvidar (via f_t) y lo que decidimos aprender (via i_t y \u0303C_t).")

# Puerta de salida o_t
o_t = sigmoid(W_o @ concat + b_o)
print("\n📤 Puerta de SALIDA o_t (cuánto mostrar) ===\n", o_t)
print("Nota: valores cercanos a 1 permiten que el contenido actual de la celda se refleje en la salida h_t, mientras que valores bajos lo ocultan.")

# Estado oculto h_t
h_t = o_t * tanh(C_t)
print("\n📣 SALIDA h_t (estado oculto actual) ===\n", h_t)
print("Nota: h_t es la salida visible de esta celda LSTM. Depende de cuánto dejemos salir (o_t) y del estado actual de la memoria (C_t).")


🔑 Puerta de OLVIDO f_t (cuánto olvidar del pasado) ===
 [[0.71953755]
 [0.73617388]
 [0.90950893]]
Nota: valores cercanos a 1 mantienen la memoria anterior (C_{t-1}), mientras que valores cercanos a 0 la olvidan.

🆕 Puerta de ENTRADA i_t (cuánto nuevo aprender) ===
 [[0.90876682]
 [0.81611384]
 [0.92843489]]
Nota: valores cercanos a 1 permiten que la nueva información propuesta (̃C_t) entre a la memoria; valores cercanos a 0 la bloquean.

📥 Estado CANDIDATO ̃C_t (información propuesta) ===
 [[0.90783988]
 [0.99039234]
 [0.9685002 ]]
Nota: este es el nuevo contenido que podría ser guardado en la celda, sujeto a la aprobación de i_t.

🧠 ESTADO de CELDA C_t (memoria combinada) ===
 [[1.44826102]
 [1.25079807]
 [1.54318771]]
Nota: C_t combina lo que decidimos olvidar (via f_t) y lo que decidimos aprender (via i_t y ̃C_t).

📤 Puerta de SALIDA o_t (cuánto mostrar) ===
 [[0.91693716]
 [0.93818735]
 [0.75460941]]
Nota: valores cercanos a 1 permiten que el contenido actual de la celda se refle